### ISSUE TITLE
Incorrect data due to CUSIP change

### ISSUE THREAD

**Issue by deAtog** [guanquann/Stocksera#22]
On October 6th, XERS merged with SBBP and the combined company was relisted under a new CUSIP ID with a symbol of XERS. The SEC shows that the combined company had [234k FTDs on October 6th](https://sec.report/fails.php?tc=xers). In the data file provided from the SEC, the ticker symbol of the new company briefly becomes XERSZZZZ while the old has a ticker symbol of XERS for that day.  From October 6th forward in the SEC data,  XERS has a new CUSIP number. In my opinion you should try to separate the data based on CUSIP IDs as XERS before the merge is different from XERS after. I believe the FTDs listed under the new CUSIP are a combined total of FTDs from the old XERS and SBBP tickers with SBBP's FTDs converted to shares of the new XERS.

The data from the SEC contains the following:
```
20211006|98422E103|XERSZZZZ|243466|XERIS BIOPHARMA HLDGS INC COM |0.01
20211006|98422L107|XERS|1350|XERIS PHARMACEUTICALS INC|2.37
20211007|98422E103|XERS|9463|XERIS BIOPHARMA HLDGS INC COM |2.36
```

**Comment by CodeInFilth** [comment]
there will always be a changing amoutn of tickers imo we manage this if we want to dev
