### ISSUE TITLE
Always missing one script :(

### ISSUE THREAD

**Issue by CodeInFilth** [guanquann/Stocksera#26]
It seems no matter how up to date I am always missing one file you plan to release but didn't comment out, maybe you intended to leave it so people understand what is coming soon? For myself it makes me feel as-though my package is not complete.

The two files `scheduled_tasks/get_crypto_transactions.py` and `scheduled_tasks/get_ipo_calendar.py` are included in your .gitignore file. Causing issues when using `scheduled_tasks`. 

I must comment out line 33, 105, 210, 211 inside `tasks_to_run.py`. 

Typically I wouldn't have an issue with this but the discover page and all related _get_ipo_calandar_ files seem to be included and/or have references to this missing file(s). I have removed the lines that caused errors but perhaps uploading this even if its less stable would be helpful.

### files that are referencing `get_ipo_calendar.py`
`static/javascript/discover/ipo.js`
`templates/discover/ipo_calendar.html`
`ViewStocks/views.py`
`templates/discover/short_interest.html`
`ViewStocks/urls.py`

If you didnt mean to forget this file where are you pulling information from so I may recreate this myself?

**Comment by guanquann** [comment]
Added them to the latest commit. After you run get_ipo_calendar.py, view it in /ipo_calendar. get_crypto_transactions.py currently only gets transactions from whalealert.io
