### ISSUE TITLE
Using Mysql on Docker with new changes

### ISSUE THREAD

**Issue by CodeInFilth** [guanquann/Stocksera#30]
I want to transfer your old sqlite version to to the new mysql version and give the new code a try but cant figure out how to get docker to install mysql in the dockerfile or what steps to take.

**Comment by CodeInFilth** [comment]
Bassically if it is possible to have a small video on how to run a docker mysql container in the background or how to setup the server from a to Z and i would deffintaly think people would consider donating more. !!! please continue your work!! :)

I am sorry I have needed so much help aha

**Comment by guanquann** [comment]
I might have unintentionally neglected the dockerisation part previously when i migrate the database to mysql. I have pushed a new commit with the new docker commands.

```
# Clone the project
git clone https://github.com/guanquann/Stocksera.git

# Dockerise
docker-compose build

docker-compose up

docker-compose run --rm web python3 manage.py migrate

docker compose run --rm web python scheduled_tasks/create_database.py

docker compose run --rm web python tasks_to_run.py
```
