### ISSUE TITLE
/short_interest/ source?

### ISSUE THREAD

**Issue by robdevops** [guanquann/Stocksera#33]
The Stocksera README hyperlink text says short_interest data is from shortinterest.com, however, the hyperlink target is highshortinterest.com.

Stocksera data has a short interest of >15% but highshortinterest.com supplies only >20%.
shortinterest.com appears to be domain parked.

What is the current data source?

**Comment by guanquann** [comment]
Hello, apologies as the readme is not updated. The current data source is from https://www.stockgrid.io/get_short_interest. You can view the code at https://github.com/guanquann/Stocksera/blob/master/scheduled_tasks/discover/miscellaneous.py
