### ISSUE TITLE
Full list of data sources?

### ISSUE THREAD

**Issue by datatalking** [guanquann/Stocksera#34]
I've just found your repo today and was looking for a list of dates or list of data sources that Stocksera is currently setup to handle. If this has not been created, where could I start building that list and I will generate a PR.

What are some features or documentation that I could start contributing?

**Comment by guanquann** [comment]
For more information on how to set up Stocksera locally, refer to the bottom of https://github.com/guanquann/Stocksera and https://github.com/guanquann/Stocksera/tree/master/scheduled_tasks. If you have a better way, please let me know
