### ISSUE TITLE
Options expiration date list expands when selecting new date

### ISSUE THREAD

**Issue by chatico** [guanquann/Stocksera#36]
Hi, I noticed the following issue on the Stock Options page: If you select an expiration date from the expiration date list, the list will expand with a duplicate of all the previous dates.

Steps to reproduce:
1. Select a stock and go to Stock => Options
2. Open the expiration date list, you can see that here are certain dates listed
3. Select an expiration date from the list
4. Open the expiration date list again and you will see that it's expanded with exactly the same dates (duplicate)

**Comment by guanquann** [comment]
Hello there! I can't seem to replicate your issue. Perhaps you can list down the ticker and date you tried. Thanks.

![Screenshot 2022-11-01 231014](https://user-images.githubusercontent.com/76832850/199267153-078ce719-3f0a-4321-9098-4af44f1e7dc8.png)

**Comment by chatico** [comment]
Hi, Thanks for looking at the issue. It happens normally on every ticker I tried. It also happend with AAPL.

I can see that the issue appears in your screenshot. The last entry of the list is the same as the first entry of the list, you can also scroll down now and see a fully duplicated appended list.

**Comment by guanquann** [comment]
Issue solved. Sorry for the late update
