### ISSUE TITLE
Yahoo v7 issue as of last month

### ISSUE THREAD

**Issue by CodeInFilth** [guanquann/Stocksera#41]
change the fast yahoo to v6 for fix

**Comment by guanquann** [comment]
I'm assuming you are talking about /scheduled_tasks/reddit/stocks/fast_yahoo.py. I also noticed the error last month, but have no idea how to fix it. Changing it from v7 to v6 still does not work for me.

**Comment by CodeInFilth** [comment]
Yes I am, intresting yea. if you google it many reddit users also having this issue. maybe let some people know v7 wont work for me currently

**Comment by guanquann** [comment]
I have fixed the fast_yahoo issue. Please use the latest commit version.
